# Generated by Django 5.1.2 on 2024-10-26 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("address", models.CharField(max_length=256)),
                ("facilities", models.CharField(max_length=512)),
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("contact_number", models.CharField(max_length=12)),
                ("contact_email", models.EmailField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("user_type", models.CharField(default="User", max_length=20)),
                ("dob", models.DateField()),
                ("gender", models.CharField(default="M", max_length=2)),
                ("pref_smoking", models.CharField(default="N", max_length=2)),
                ("pref_drinking", models.CharField(default="N", max_length=2)),
                ("pref_veg", models.CharField(default="N", max_length=2)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Flat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("availability", models.BooleanField(default=False)),
                ("rent_per_room", models.IntegerField()),
                ("floor_number", models.IntegerField()),
                ("flat_number", models.IntegerField()),
                (
                    "flat_identifier",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "associated_apt_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="housing.apartment",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("tenant_name", models.CharField(max_length=100)),
                (
                    "flat_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.flat",
                    ),
                ),
                (
                    "ownername",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interested",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartment_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.apartment",
                    ),
                ),
                (
                    "flat_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.flat",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="housing.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apartment",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="housing.user",
            ),
        ),
    ]
