"""
    Modifying email field 
"""

# Generated by Django 4.1.1 on 2022-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    """
        Modifying email field
    """

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contact_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
