# Generated by Django 5.1.2 on 2024-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(max_length=30),
        ),
    ]
