# Generated by Django 5.1.2 on 2024-10-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0002_alter_user_contact_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flat",
            old_name="username",
            new_name="ownername",
        ),
    ]
