# Generated by Django 5.1.2 on 2024-10-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0003_rename_username_flat_ownername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="flat_identifier",
            field=models.CharField(
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
