"""
    Updated housing Database 
"""

# Generated by Django 4.1.1 on 2022-10-09 13:47

from django.db import migrations


class Migration(migrations.Migration):
    """
    Updated housing Database 
    """

    dependencies = [
        ('housing', '0002_alter_owner_contact_email_alter_user_contact_email'),
        ('housing', '0003_alter_interested_flat_id'),
    ]

    operations = [
    ]
