# Generated by Django 5.1.2 on 2024-10-26 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_alter_flat_flat_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="lease_identifier",
            field=models.CharField(
                default=None,
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="associated_apt_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="housing.apartment"
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
