# Generated by Django 5.1.2 on 2024-10-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_merge_20221009_1347"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantsRights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="owner",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="owner",
            name="reviews",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housing.owner",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="associated_apt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="housing.apartment"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="lease_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housing.lease",
            ),
        ),
    ]
