# Generated by Django 5.1.2 on 2024-10-26 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0004_merge_20221009_1347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housing.owner",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="associated_apt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="housing.apartment"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="lease_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housing.lease",
            ),
        ),
    ]
