# Generated by Django 5.1.2 on 2024-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0005_alter_apartment_owner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
