# Generated by Django 5.1.2 on 2024-10-26 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0005_lease_lease_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interested",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
