# Generated by Django 5.1.2 on 2024-10-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0006_user_is_active_user_is_staff_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="flat_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housing.flat",
            ),
        ),
    ]
