# Generated by Django 5.1.2 on 2024-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0007_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="is_signed",
            field=models.BooleanField(default=False),
        ),
    ]
